UI/Areas/Admin/Controllers/NotificationsController.cs
using Application.Contracts;
using Application.Dots;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace UI.Areas.Admin.Controllers
{
    [Area("Admin")]
     
    public class NotificationsController : Controller
    {
        private readonly INotificationService _notificationService;
        private readonly ICustomerService _customerService;
        public NotificationsController(INotificationService notificationService, ICustomerService customerService)
        {
            _notificationService = notificationService;
            _customerService = customerService;
        }
        public IActionResult Index()
        {
            var listNotifications = _notificationService.GetAll();
            return View(listNotifications );
        }
        public  IActionResult Edit(int id)
        {
            var listCustomers = new SelectList(_customerService.GetAll(), "Id", "FirstName");
          ViewBag.listCustomers = listCustomers;
            var  notification = new TbNotificattionDTO();
            if (id != 0)
            {
                notification = _notificationService.GetById(id);
            }
            return View(notification);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save(TbNotificattionDTO notification)
        {
            if (!ModelState.IsValid)
                return View("Edit", notification);
            if (notification.Id == 0)
            {
               // notification.CustomerId = 1; 
                _notificationService.Add(notification);
            }
            else
            {
                _notificationService.Update(notification);
            }
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            _notificationService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

UI/Areas/Admin/Views/Notifications/Edit.cshtml
@model TbNotificattionDTO


<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title"> form Notification </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#"></a></li>
                <li class="breadcrumb-item active" aria-current="page"></li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-md-8 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title"></h4>
                    <p class="card-description">  </p>
                    <form class="forms-sample" method="post" enctype="multipart/form-data"
                          asp-controller="Notifications" asp-action="Save" role="form">
                        <input asp-for="Id" type="hidden" />

                      
                        <div class="form-group">
                            <label asp-for="CustomerId"></label>
                            <select asp-for="CustomerId" class="form-control"
                                    asp-items="ViewBag.ListCustomers" required>
                                <option value="">-- Select Customer --</option>

                            </select>
                            <span asp-validation-for="CustomerId" class="text-danger"></span>
                        </div>
              



                        <div class="form-group ">
                            <label for="exampleInputUsername1"> Message</label>
                            <input asp-for="Message   " type="text " class="form-control" placeholder="Message">
                            <span asp-validation-for="Message"></span>
                        </div>

                        <div class="form-group ">
                            <label for="exampleInputUsername1">Notification Type</label>
                            <input asp-for="NotificationType    " type="text " class="form-control" placeholder="Notification Type">
                            <span asp-validation-for="Message"></span>
                        </div>

                        <div class="form-group ">
                            <label for="exampleInputUsername1"> IsRead</label>
                            <input asp-for="IsRead   " type="text " class="form-control" placeholder="IsRead">
                            <span asp-validation-for="IsRead"></span>
                        </div>
                      
                        <button type="submit" formmethod="post" class="btn btn-gradient-primary me-2">Save</button>
                        <button class="btn btn-light">New</button>
                    </form>
                </div>
            </div>
        </div>


    </div>
</div>

@section Scripts
{

}

UI/Areas/Admin/Views/Notifications/Index.cshtml
@model List<TbNotificattionDTO   >



<div class="container-scroller">

    <div class="container-fluid page-body-wrapper">
        <div class="main-panel">
            <div class="content-wrapper">
                <div class="page-header">
                    <h3 class="page-title"> Notifications</h3>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#"></a></li>
                            <li class="breadcrumb-item active" aria-current="page">Data Notification</li>
                        </ol>
                    </nav>
                </div>
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Notifications</h4>
                        <div class="row">
                            <div class="col-12">
                                <a asp-controller="Notifications" asp-action="Edit" class="btn btn-success btn-fw">New</a>
                                <table id="order-listing" class="table">
                                    <thead>
                                        <tr>
                                            <th> Message</th>

                                            <th>Notification Type</th>
                                            <th>IsRead</th>
                                        
                                            <th>Actions</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>@item.Message </td>
                                                <td>
                                                    @item.NotificationType
                                                </td>
                                                <td>@item.IsRead </td>
                                              

                                                <td class="col-md-4" style="margin:0px;padding:0px;">
                                                    <a style="height:max-content"
                                                       asp-controller="Notifications" asp-action="Edit" asp-route-id="@item.Id"
                                                       class="btn btn-info btn-fw">Edit</a>


                                                    <a asp-controller="Notifications" asp-action="Delete" asp-route-id="@item.Id"
                                                       class="btn btn-danger btn-fw"
                                                       onclick="return confirm(" Are you sure");">Delete</a>
                                                </td>

                                            </tr>
                                        }




                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- content-wrapper ends -->
            <!-- partial -->
        </div>
        <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
    @section Scripts {
        <!-- Plugin js for this page -->
        <script src="~/admin/assets/vendors/datatables.net/jquery.dataTables.js"></script>
        <script src="~/admin/assets/vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script>
        <!-- End plugin js for this page -->
        <!-- Custom js for this page -->
        <script src="~/admin/assets/js/data-table.js"></script>
        <!-- End custom js for this page -->
    }